name: Clippy

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - name: clippy
      uses: bltavares/actions/clippy@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        job-name: clippy
