name: Rust

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install rust
      shell: bash
      run: |
        if hash rustup 2>/dev/null; then
          rustup update
        else
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          mv $HOME/.cargo/bin/* /usr/local/bin
        fi
    - name: Check rust version
      run: rustc -Vv && cargo -V
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose
    - name: Install rustfmt and clippy
      run: rustup component add rustfmt clippy
    - name: Run rustfmt
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all
