name: Rust

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rustfmt:
    name: rustfmt
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: install rust
      shell: bash
      run: |
        if hash rustup 2>/dev/null; then
          rustup update
        else
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          mv $HOME/.cargo/bin/* /usr/local/bin
        fi
    - name: install rustfmt
      run: rustup component add rustfmt
    - name: check rustfmt version
      run: cargo rustfmt --version
    - name: run rustfmt
      run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: install rust
      shell: bash
      run: |
        if hash rustup 2>/dev/null; then
          rustup update
        else
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          mv $HOME/.cargo/bin/* /usr/local/bin
        fi
    - name: install clippy
      run: rustup component add clippy
    - name: check clippy version
      run: cargo clippy --version
    - name: run clippy
      run: cargo clippy --all

  build:
    name: build
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: install rust
      shell: bash
      run: |
        if hash rustup 2>/dev/null; then
          rustup update
        else
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          mv $HOME/.cargo/bin/* /usr/local/bin
        fi
    - name: check rust version
      run: rustc -Vv && cargo -V
    - name: run build
      run: cargo build --all --verbose
    - name: run tests
      run: cargo test --all --verbose
